---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-namespace
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: "sql-data"
          hostPath:
            path: "/var/lib/sql"
        - name: config-volume
          configMap:
            name: mysql-config
      containers:
        - image: mysql:5.6
          name: mysql
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: "sql-data"
            - name: config-volume
              mountPath: /config
          env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: random-root-password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-service
  namespace: mysql-namespace
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql-namespace
data:
    random-root-password: "1"
    database: exampledb
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-namespace
data:
  MYSQL_PASSWORD: ZXhhbXBsZXBhc3M=
  MYSQL_USER: ZXhhbXBsZXVzZXI=
